id = "vscode-icons-original"
name = "VSCode Icons for Zed"
version = "12.15.0"
schema_version = 1
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
description = "Original vscode-icons, reimagined for Zed"
repository = "https://github.com/vscode-icons/vscode-icons-zed"
